

name: Deploy Nginx

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:

    - name: Get Azure VM Name
      run: |
        VM_NAME=$(curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-01-01" | jq -r .compute.name)
        echo "VM_NAME=$VM_NAME" >> $GITHUB_ENV
        echo $VM_NAME
    - name: code checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
  
    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        TAG: ${{github.sha}}
      run: |
        gcloud auth configure-docker us-east1-docker.pkg.dev
        docker build -t us-east1-docker.pkg.dev/$GOOGLE_PROJECT/pdp-test4/go-demo:$TAG .
        docker push us-east1-docker.pkg.dev/$GOOGLE_PROJECT/pdp-test4/go-demo:$TAG

    - name: Choreo Deploy
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        REPO_NAME: ${{ github.event.repository.name }}
        TAG: ${{github.sha}}
        TOKEN: ${{secrets.TOKEN}}
        DOCKER_IMAGE_NAME: ${{secrets.DOCKER_USER}}/wipro
      run: |
        curl --location --request POST \
        'https://apis.preview-dv.choreo.dev/devops/1.0.0/external-ci/deploy' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "component_id": "c46972fb-d7cb-485e-9df4-5747510edebb",
          "version_id": "6e4d65c8-8509-43ef-83b9-e54e0640a8db",
          "token": "'${TOKEN}'",
          "image": "us-east1-docker.pkg.dev/'${GOOGLE_PROJECT}'/pdp-test4/go-demo:'${TAG}'"
        }'
