# name: Docker Image CI

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: docker login
#         env:
#           DOCKER_USER: ${{secrets.DOCKER_USER}}
#           DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#         run: |
#           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#       - name: Build the Docker image
#         env:
#           DOCKER_USER: ${{secrets.DOCKER_USER}}
#           REPO_NAME: ${{ github.event.repository.name }}
#           TAG: ${{github.sha}}
#         run: docker build . --file Dockerfile --tag ${DOCKER_USER}/wipro:${TAG}
#       - name: Docker Push
#         run: docker push ${DOCKER_USER}/wipro:${TAG}
#         env:
#           DOCKER_USER: ${{secrets.DOCKER_USER}}
#           REPO_NAME: ${{ github.event.repository.name }}
#           TAG: ${{github.sha}}
#       - name: Choreo Deploy
#         env:
#           DOCKER_USER: ${{secrets.DOCKER_USER}}
#           REPO_NAME: ${{ github.event.repository.name }}
#           TAG: ${{github.sha}}
#           TOKEN: ${{secrets.TOKEN}}
#           DOCKER_IMAGE_NAME: ${{secrets.DOCKER_USER}}/wipro
#         run: |
#           curl --location --request POST \
#           'https://apis.preview-dv.choreo.dev/devops/1.0.0/external-ci/deploy' \
#           --header 'Content-Type: application/json' \
#           --data-raw '{
#             "component_id": "bf7d9d04-0c95-4ede-995e-b40f51e8ced1",
#             "version_id": "dacf2c8b-6e2b-41b7-8e7b-e6887a4cb250",
#             "token": "'${TOKEN}'",
#             "image": "registry.docker.com/'${DOCKER_IMAGE_NAME}':'${TAG}'"
#           }'
